// Copyright (c) 1998, 2019, Oracle and/or its affiliates. All rights reserved.

// Applet Selection APDU Script
//
// Package:     SCACAuth_Applets.uned.ebs.scacauth
// Package AID: //aid/8578696895/696683
// Applet:      uned.ebs.scacauth.SCACAuth
// Applet AID:  //aid/8578696895/69668301
//

// Select uned.ebs.scacauth.SCACAuth applet
0x00 0xA4 0x04 0x00 0x09 0x85 0x78 0x69 0x68 0x95 0x69 0x66 0x83 0x01 0x7F;
